from __future__ import annotations

from pathlib import Path

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from app.models.receipt import Receipt

FONT_NAME = "Helvetica"

try:
    pdfmetrics.registerFont(
        TTFont(
            "DejaVu",
            "fonts/DejaVuSans.ttf",
        )
    )
    FONT_NAME = "DejaVu"
except Exception:
    pass

BASE_DIR = Path("storage")

RECEIPT_DIR = BASE_DIR / "receipts"

RECEIPT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

def generate_receipt_pdf(
    receipt: Receipt,
) -> str:
    filename = f"{receipt.receipt_number}.pdf"

    pdf_path = RECEIPT_DIR / filename

    doc = SimpleDocTemplate(
        str(pdf_path),
        rightMargin=18,
        leftMargin=18,
        topMargin=20,
        bottomMargin=20,
    )

    styles = getSampleStyleSheet()

    title = styles["Heading1"]

    title.alignment = TA_CENTER

    title.fontName = FONT_NAME

    heading = styles["Heading2"]

    heading.fontName = FONT_NAME

    normal = styles["BodyText"]

    normal.fontName = FONT_NAME

    right = styles["BodyText"]

    right.alignment = TA_RIGHT

    right.fontName = FONT_NAME

    story = []

    story.append(
        Paragraph(
            "Seed of Abraham Technologies",
            title,
        )
    )

    story.append(
        Paragraph(
            "OFFICIAL PAYMENT RECEIPT",
            heading,
        )
    )

    story.append(
        Spacer(
            1,
            8 * mm,
        )
    )

    story.append(
        Paragraph(
            f"<b>Receipt Number:</b> {receipt.receipt_number}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Date Issued:</b> {receipt.issued_at:%d %B %Y %H:%M}",
            normal,
        )
    )

    story.append(
        Spacer(
            1,
            6 * mm,
        )
    )

    table = Table(
        [
            ["Invoice", str(receipt.invoice_id)],
            ["Payment", str(receipt.payment_id)],
            ["School", str(receipt.school.name)],
            ["Customer", str(receipt.customer.name)],
            ["Amount", f"{receipt.currency} {receipt.amount:,.2f}"],
            ["Status", receipt.status.title()],
        ],
        colWidths=[
            60 * mm,
            110 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0,0), (-1,0), HexColor("#0d6efd")),
                ("GRID",(0,0),(-1,-1),0.5,HexColor("#dcdcdc")),
                ("BOTTOMPADDING",(0,0),(-1,-1),8),
                ("TOPPADDING",(0,0),(-1,-1),8),
                ("FONTNAME",(0,0),(-1,-1),FONT_NAME),
            ]
        )
    )

    story.append(table)

    story.append(
        Spacer(
            1,
            12 * mm,
        )
    )

    story.append(
        Paragraph(
            "Thank you for your payment.",
            heading,
        )
    )

    story.append(
        Paragraph(
            "This receipt was automatically generated by the Seed of Abraham Licensing Server.",
            normal,
        )
    )
    doc.build(story)
    return str(pdf_path)
