"""update admin autogenerate id

Revision ID: 23d760c3b07e
Revises: 8b87faa6eda1
Create Date: 2026-07-11 07:45:48.571400
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d760c3b07e'
down_revision = '8b87faa6eda1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_id', table_name='admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    # ### end Alembic commands ###
