"""remoce ceckout_url from purchaseSession

Revision ID: 59e7c4d5f192
Revises: 361eb323ed31
Create Date: 2026-08-06 23:56:21.504917
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e7c4d5f192'
down_revision = '361eb323ed31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_sessions', 'checkout_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_sessions', sa.Column('checkout_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
