"""add purchase tokens

Revision ID: c6cdd600a6ef
Revises: b26789079e20
Create Date: 2026-08-04 23:52:47.944396
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cdd600a6ef'
down_revision = 'b26789079e20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_nonces_nonce'), 'request_nonces', ['nonce'], unique=True)
    op.create_table('license_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_downloads_token'), 'license_downloads', ['token'], unique=True)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('installation_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activation_tokens', sa.Column('download_nonce', sa.String(length=128), nullable=True))
    op.add_column('activation_tokens', sa.Column('download_nonce_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activation_tokens', sa.Column('download_nonce_used_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_activation_tokens_download_nonce'), 'activation_tokens', ['download_nonce'], unique=True)
    op.add_column('payments', sa.Column('authorization_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=500), nullable=True))
    op.add_column('purchase_sessions', sa.Column('poll_token', sa.String(length=128), nullable=False))
    op.add_column('purchase_sessions', sa.Column('checkout_token', sa.String(length=100), nullable=False))
    op.add_column('purchase_sessions', sa.Column('checkout_url', sa.String(length=500), nullable=False))
    op.create_index(op.f('ix_purchase_sessions_checkout_token'), 'purchase_sessions', ['checkout_token'], unique=True)
    op.create_index(op.f('ix_purchase_sessions_poll_token'), 'purchase_sessions', ['poll_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_sessions_poll_token'), table_name='purchase_sessions')
    op.drop_index(op.f('ix_purchase_sessions_checkout_token'), table_name='purchase_sessions')
    op.drop_column('purchase_sessions', 'checkout_url')
    op.drop_column('purchase_sessions', 'checkout_token')
    op.drop_column('purchase_sessions', 'poll_token')
    op.drop_column('payments', 'idempotency_key')
    op.drop_column('payments', 'authorization_url')
    op.drop_index(op.f('ix_activation_tokens_download_nonce'), table_name='activation_tokens')
    op.drop_column('activation_tokens', 'download_nonce_used_at')
    op.drop_column('activation_tokens', 'download_nonce_expires_at')
    op.drop_column('activation_tokens', 'download_nonce')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_license_downloads_token'), table_name='license_downloads')
    op.drop_table('license_downloads')
    op.drop_index(op.f('ix_request_nonces_nonce'), table_name='request_nonces')
    op.drop_table('request_nonces')
    # ### end Alembic commands ###
