"""add checkout_url to purchaseSession

Revision ID: c94620f65801
Revises: 59e7c4d5f192
Create Date: 2026-08-07 00:20:35.829842
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94620f65801'
down_revision = '59e7c4d5f192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_sessions', sa.Column('checkout_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_sessions', 'checkout_url')
    # ### end Alembic commands ###
