CREATE TABLE IF NOT EXISTS theory_assessments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,test_id INT NOT NULL,instructions TEXT NULL,marking_mode VARCHAR(40) NOT NULL DEFAULT 'offline_ai',ai_model VARCHAR(150) NULL,ai_model_version VARCHAR(100) NULL,status VARCHAR(30) NOT NULL DEFAULT 'draft',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_theory_test (test_id),CONSTRAINT fk_theory_assessment_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_questions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,theory_assessment_id BIGINT UNSIGNED NOT NULL,question_number INT UNSIGNED NOT NULL,question_text LONGTEXT NOT NULL,maximum_marks DECIMAL(8,2) NOT NULL,answer_guidance LONGTEXT NULL,allow_ai_knowledge BOOLEAN NOT NULL DEFAULT TRUE,metadata JSON NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_theory_question_number (theory_assessment_id,question_number),CONSTRAINT fk_theory_question_assessment FOREIGN KEY (theory_assessment_id) REFERENCES theory_assessments(id) ON DELETE CASCADE,CHECK (maximum_marks > 0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_submissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,theory_assessment_id BIGINT UNSIGNED NOT NULL,student_id INT NOT NULL,started_at DATETIME NULL,submitted_at DATETIME NULL,status VARCHAR(30) NOT NULL DEFAULT 'in_progress',total_marks DECIMAL(10,2) NULL,maximum_marks DECIMAL(10,2) NULL,grading_status VARCHAR(30) NOT NULL DEFAULT 'pending',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_theory_submission_student (theory_assessment_id,student_id),CONSTRAINT fk_theory_submission_assessment FOREIGN KEY (theory_assessment_id) REFERENCES theory_assessments(id) ON DELETE CASCADE,CONSTRAINT fk_theory_submission_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_answers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,submission_id BIGINT UNSIGNED NOT NULL,theory_question_id BIGINT UNSIGNED NOT NULL,answer_text LONGTEXT NOT NULL,word_count INT UNSIGNED NOT NULL DEFAULT 0,submitted_at DATETIME NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_theory_answer (submission_id,theory_question_id),CONSTRAINT fk_theory_answer_submission FOREIGN KEY (submission_id) REFERENCES theory_submissions(id) ON DELETE CASCADE,CONSTRAINT fk_theory_answer_question FOREIGN KEY (theory_question_id) REFERENCES theory_questions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_marks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,answer_id BIGINT UNSIGNED NOT NULL,awarded_marks DECIMAL(8,2) NOT NULL DEFAULT 0,maximum_marks DECIMAL(8,2) NOT NULL,percentage DECIMAL(7,3) NOT NULL DEFAULT 0,confidence DECIMAL(5,4) NULL,relevance_score DECIMAL(5,4) NULL,correctness_score DECIMAL(5,4) NULL,completeness_score DECIMAL(5,4) NULL,understanding_score DECIMAL(5,4) NULL,explanation LONGTEXT NULL,strengths LONGTEXT NULL,weaknesses LONGTEXT NULL,missing_points LONGTEXT NULL,grading_model VARCHAR(150) NULL,grading_model_version VARCHAR(100) NULL,grading_prompt_version VARCHAR(50) NULL,status VARCHAR(30) NOT NULL DEFAULT 'ai_provisional',graded_at DATETIME NULL,reviewed_by INT NULL,reviewed_at DATETIME NULL,review_reason TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_theory_mark_answer (answer_id),CONSTRAINT fk_theory_mark_answer FOREIGN KEY (answer_id) REFERENCES theory_answers(id) ON DELETE CASCADE,CHECK (awarded_marks >= 0),CHECK (awarded_marks <= maximum_marks),CHECK (percentage >= 0 AND percentage <= 100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_grading_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,submission_id BIGINT UNSIGNED NOT NULL,model_name VARCHAR(150) NOT NULL,model_version VARCHAR(100) NULL,prompt_version VARCHAR(50) NOT NULL,runtime VARCHAR(100) NOT NULL DEFAULT 'ollama',started_at DATETIME NOT NULL,completed_at DATETIME NULL,status VARCHAR(30) NOT NULL DEFAULT 'running',error_message TEXT NULL,metadata JSON NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_theory_run_submission FOREIGN KEY (submission_id) REFERENCES theory_submissions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_grading_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,grading_run_id BIGINT UNSIGNED NOT NULL,answer_id BIGINT UNSIGNED NULL,event_type VARCHAR(50) NOT NULL,event_data JSON NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_theory_event_run FOREIGN KEY (grading_run_id) REFERENCES theory_grading_runs(id) ON DELETE CASCADE,CONSTRAINT fk_theory_event_answer FOREIGN KEY (answer_id) REFERENCES theory_answers(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_ai_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,institution_id BIGINT UNSIGNED NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,provider VARCHAR(50) NOT NULL DEFAULT 'ollama',model_name VARCHAR(150) NOT NULL DEFAULT 'qwen1.7b',embedding_model VARCHAR(150) NULL DEFAULT 'nomic-embed-text',endpoint VARCHAR(255) NOT NULL DEFAULT 'http://127.0.0.1:11434',timeout_seconds INT UNSIGNED NOT NULL DEFAULT 300,temperature DECIMAL(4,3) NOT NULL DEFAULT 0.1,max_retries TINYINT UNSIGNED NOT NULL DEFAULT 2,metadata JSON NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_theory_ai_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_ai_knowledge_sources (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,institution_id BIGINT UNSIGNED NULL,title VARCHAR(255) NOT NULL,source_type VARCHAR(50) NOT NULL DEFAULT 'local_document',file_path VARCHAR(1000) NULL,content_hash CHAR(64) NULL,indexed BOOLEAN NOT NULL DEFAULT FALSE,metadata JSON NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_theory_knowledge_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS theory_manual_reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,mark_id BIGINT UNSIGNED NOT NULL,reviewer_id INT NULL,original_awarded_marks DECIMAL(8,2) NOT NULL,final_awarded_marks DECIMAL(8,2) NOT NULL,reason TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_theory_review_mark FOREIGN KEY (mark_id) REFERENCES theory_marks(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;